### PR TITLE
Fix test for bad chunk data to allow for 0-sample deep chunks

### PR DESCRIPTION
**Pull request by kdt3rd**
Signed-off-by: Kimball Thurston <kdt3rd@gmail.com>

### CODE REVIEW

**Comment by lgritz** [comment]
I don't understand this part of the code at all, but something about the structure of the change seems odd to me.

There are a number of tests that look like this

    if (condition)
        error;

and this PR changes those to

    if (condition || other_conditions)
        error;

Please help me understand how *strictly expanding* the set of circumstances that are considered an error will fix the bug wherein a correct file has been incorrectly flagged as an error? If you are just using `||` to catch more conditions, won't the same false positive still occur?

**Comment by kdt3rd** [comment]
well, it was if value <= 0 before, I've changed it to if value < 0 OR (equal 0 AND the other value != 0) instead of just the <= test

**Comment by lgritz** [comment]
Aha, of course. Two of the places you changed were < before and still after, and two changed from <= to <, and I did not notice that. OK, all looks good.

**Review by lgritz — APPROVED** [review]

**Comment by kdt3rd** [comment]
yeah, I basically added other guards for the other values - the first one for the packed size we had added was due to a fuzz report, the other cases I added would be exposed by other fuzz tests that hadn't yet been triggered - pre-fixing failures

**Comment by lgritz** [comment]
Woo-hoo! OIIO bleeding edge tests passed last night!

**Pull request merged**
