### PR TITLE
Fix build script so auto-build of imath uses the new branch name

### PR DESCRIPTION
**Pull request by lgritz**
Signed-off-by: Larry Gritz <lg@larrygritz.com>

### CODE REVIEW

**Review by cary-ilm — APPROVED** [review]

**Comment by cary-ilm** [comment]
Thanks, I'm about to submit a PR that updates everything else as well, just confirming the build, and waiting for the checks.

**Comment by lgritz** [comment]
I'm not totally sure I understand. Do you want me to merge this when the checks are finished? Or are you saying that these changes are already incorporated into another pending PR?

**Comment by kdt3rd** [comment]
fyi: I fixed the windows build earlier, clang-format had sort includes turne on, which moves windows.h around :(

**Comment by cary-ilm** [comment]
Fine to merge this when the checks pass.

**Pull request merged**
