### PR TITLE
Add Scorecard GitHub Action

### PR DESCRIPTION
**Pull request by diogoteles08**
Implemented as discussed in #1530

I've taken the liberty and also added the Scorecard badge on your README -- you're able to edit the PR so feel free to take it out if you prefer. The badge would be auto-updated for every change made to the repository and show off your hard work on security posture =). Find more info about the badge on [this blogpost](https://openssf.org/blog/2022/09/08/show-off-your-security-score-announcing-scorecards-badges/)

(Although it might not seem like it, a 7.6/10 score is a great score! It puts openexr at the top 4% of relevant projects 😄)

### CODE REVIEW

**Comment by cary-ilm** [comment]
Thanks for this, it mostly looks good and helpful but I have a few questions about some of the low-scoring times:

- Token Permissions: The message says "Warn: no topLevel permission defined: .github/workflows/python-wheels.yml:1", but isn't this the permissions you just added? When I followed the suggestion to visit " Visit https://app.stepsecurity.io/secureworkflow/AcademySoftwareFoundation/openexr/python-wheels.yml/main?enable=permissions", I don't see anything there that looks like setting permissions, am I missing something? 
- SAST - we do use SonarCloud static analysis, should that have registered?
- CII Best Practices - We do have a passing grade at https://www.bestpractices.dev/en/projects/2799, and a badge on the main repo page.
- License: Items says "Warn: Any licence detected not an FSF or OSI recognized license: LICENSE.md:1", but our license is BSD 3-Clause.
- Branch Production, Packaging, and Pinned Dependencies seem to have encountered some sort of error.


Happy to help work these issues out and integrate the scorecard, seems very much in line with the CII Badge we've already been working with.

**Comment by diogoteles08** [comment]
Very glad to hear you're open to use the action! I'll be happy to work these issues out with you.

> * Token Permissions: The message says "Warn: no topLevel permission defined: .github/workflows/python-wheels.yml:1", but isn't this the permissions you just added? When I followed the suggestion to visit " Visit https://app.stepsecurity.io/secureworkflow/AcademySoftwareFoundation/openexr/python-wheels.yml/main?enable=permissions", I don't see anything there that looks like setting permissions, am I missing something?

No, you're correct. What's happening is that the result you're seeing was generated by a cron job that happened before you merged my commit with the token permissions fix 😖. When you add the Scorecard action, every time your action run after a push on main it will also update that viewer accordingly.

> * SAST - we do use SonarCloud static analysis, should that have registered?

It most probably should! I'd be happy to understand how you're currently using it and debug/notice scorecard to know why it's not detecting. After a quick look into the [check documentation](https://github.com/ossf/scorecard/blob/51fbe15d81f7a35c10f49172010b82ad96bfd387/docs/checks.md#sast), it seems they're only checking if there are SAST checks on your last PRs. Are you currently enabling automatic SAST analysis before the PRs?

> * CII Best Practices - We do have a passing grade at https://www.bestpractices.dev/en/projects/2799, and a badge on the main repo page.
> * License: Items says "Warn: Any licence detected not an FSF or OSI recognized license: LICENSE.md:1", but our license is BSD 3-Clause.

Both cases are unfortunate, that is not working as intended. I'll be happy to take a look into that. According to scorecard documentation, you should be receiving a 5/10 on the first check and 10/10 on the second.

> * Branch Production, Packaging, and Pinned Dependencies seem to have encountered some sort of error.

1.  The branch protection check currently can't be run in our cron job because of permission restrictions, so it'll only became available on the viewer after you run Scorecard on the action.
2. Honestly I don't know why it's not retrieving a score for Packaging but I've seen this happening before and have already spotted it in [this issue](https://github.com/ossf/scorecard/issues/2763). Independent of this issue, your project would probably receive a 0/10 on this case, because AFAIU you don't have a script to automatically build your project and add it in your releases. After a quick look in your [Install guide](https://openexr.com/en/latest/install.html#build-from-source), it seems like you have easy and automatic ways to build your project, have you considered automatically building them for each release? I could surely help on that.
3. For Pinned Dependencies, it's [this known Scorecard issue](https://github.com/ossf/scorecard/issues/3075), it's happening because of this [piece of your code]
(https://github.com/AcademySoftwareFoundation/openexr/blob/main/.github/workflows/ci_workflow.yml#L292C67-L292C67). I've already sent a comment on the issue to mention it's also happening in your project.

**Review by cary-ilm — APPROVED** [review]
This is fine as a start, we can follow up as needed on specific entries.

**Comment by gabibguti** [comment]
Hi! Providing an update here, looks like the latest version of Scorecard can now identify the CII-Best-Practices badge and give a 5/10 score as Diogo mentioned.
Ref: https://securityscorecards.dev/viewer/?uri=github.com/AcademySoftwareFoundation/openexr

If you are still receiving a low score in the report, please try updating the workflow to use the latest version:
https://github.com/AcademySoftwareFoundation/openexr/blob/main/.github/workflows/scorecard.yml#L33
```yml
uses: ossf/scorecard-action@08b4669551908b1024bb425080c797723083c031 # v2.2.0
```

**Comment by cary-ilm** [comment]
Thanks, I'll update the action momentarily.

One more immediate question, the license badge in https://github.com/AcademySoftwareFoundation/openexr#readme currently says "license not identifiable by github", but it's word-for-word 3-Clause BSD. Is something amiss?

**Comment by gabibguti** [comment]
GitHub [detects the repository license](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository#detecting-a-license) using [the open source Ruby gem Licensee](https://github.com/licensee/licensee). I made some tests and looks like Licensee does not identify your BSD 3-Clause license due to [the SPDX identifiers lines](https://github.com/AcademySoftwareFoundation/openexr/blob/main/LICENSE.md?plain=1#L1-L2). If you are willing to remove the lines, the identification should work. Otherwise, I think you can add up to this issue: https://github.com/licensee/licensee/issues/635

**Comment by cary-ilm** [comment]
Thank you for that detective work, that would taken me awhile to sort out on my own!  I hope those lines aren't necessary for the license file, I'll remove them and see what happens.

**Comment by lgritz** [comment]
I think the only common sense answer possible is that the license identifier is certainly not needed for the license file itself.

**Comment by cary-ilm** [comment]
Presumably that got swept up while adding the SPDX identifiers to all files that didn't have it.

But @gabibguti, I removed the SPDX comments from LICENSE.md but the badge is still saying "license not identifiable by github."   Is something special required to get the Ruby gem badge to work on the repo? 

The GitHub page for [LICENSE.md](https://github.com/AcademySoftwareFoundation/openexr/blob/main/LICENSE.md) does recognize the license, so it appears to be just the badge?

**Comment by gabibguti** [comment]
Seems like it's working now? Maybe it was a delay or cache?

image

**Comment by cary-ilm** [comment]
Yes! It must have woken up slowly. Thanks!

**Comment by cary-ilm** [comment]
@diogoteles08, it looks like the OpenEXR scorecard action is failing, but I can't see anything in the log file to indicate why.  The action itself is failing and thus not uploading the report artifact, it's not that the project is receiving failing grades in the report. The latest run log is [here](https://github.com/AcademySoftwareFoundation/openexr/actions/runs/8383028765/job/22957954654), could you take a look and see if you can determine the cause?

**Comment by gabibguti** [comment]
Hey @cary-ilm! This PR should fix it: https://github.com/AcademySoftwareFoundation/openexr/pull/1686

**Pull request merged**
