### PR TITLE
Use posix compat code for old macOS without libdispatch

### PR DESCRIPTION
**Pull request by barracuda156**
See: https://github.com/AcademySoftwareFoundation/openexr/issues/1405

@meshula Please take a look.

### CODE REVIEW

**Review by meshula — APPROVED** [review]
this looks good to me

**Comment by barracuda156** [comment]
@meshula CIs passed, perhaps okay to merge?

**Review by meshula — APPROVED** [review]

**Comment by meshula** [comment]
@cary-ilm @kdt3rd This one fixes building on macos 10.5 and earlier, and is one of the fixes on the way to getting ppc working. Any comments? I think this is ready to land.

**Comment by barracuda156** [comment]
> @cary-ilm @kdt3rd This one fixes building on macos 10.5 and earlier, and is one of the fixes on the way to getting ppc working. Any comments? I think this is ready to land.

For the record, it is also relevant for 10.6 ppc (native and Rosetta).

P. S. At the moment I am less sure about 10.4 status, but I can try building it.

**Comment by kdt3rd** [comment]
Thanks! And here I thought I was on an old version of macOS on my 2012 macbook :)

**Comment by barracuda156** [comment]
@kdt3rd Thank you!

**Pull request merged**
