### PR TITLE
Remove unused variable _maxScanLineSize from B44Compressor

### PR DESCRIPTION
**Pull request by Vertexwahn**
Remove unused variable _maxScanLineSize from B44Compressor

### CODE REVIEW

**Comment by kdt3rd** [comment]
there are actually a few of these around, just fyi. We had been delaying doing this (there are a couple of "TODO" comments) to avoid changing ABI from some of the public classes, but probably should go ahead given we aren't doing namespace versioning (although we should think about that in the future).

**Review by meshula — APPROVED** [review]

**Comment by Vertexwahn** [comment]
Do not want to break the ABI -> close PR

**Comment by lgritz** [comment]
We could at least add a comment in the header to indicate that it's unused and should be removed next time we're at a release in which it's ok to break the ABI.

**Comment by Vertexwahn** [comment]
Reopened PR: Instead of removing there is now a comment that this should be cleaned up, once its safe to break the ABI

**Pull request closed without merging**
