### PR TITLE
Fix a typo breaking the link to Imath repository in readme

### PR DESCRIPTION
**Pull request by illwieckz**
Fix a typo breaking the link to lmath repository in readme

### CODE REVIEW

**Comment by meshula** [comment]
Thanks for spotting that. Since the bot is flagging CLA, do you want to go ahead and do that? Or we can poke the fix in manually if you'd like to avoid the bother?

**Comment by illwieckz** [comment]
> Thanks for spotting that. Since the bot is flagging CLA, do you want to go ahead and do that? Or we can poke the fix in manually if you'd like to avoid the bother?

It's done. 🙂️

**Comment by illwieckz** [comment]
I just edited the title because I wrote Lmath instead of Imath

**Review by meshula — APPROVED** [review]

**Comment by meshula** [comment]
Thanks!

**Pull request merged**
