### PR TITLE
Reduce warnings reported in #982

### PR DESCRIPTION
**Pull request by nporcino-pixar**
This change reduces the number of warnings reported in #982 by approximately 400 lines. I will continue to add to this as time allows.

I suggest a msvc warning clean up target a point release, rather 3.0.

points for discussion

- there might be a way to cure the 4251/4275 warnings, but I haven't discovered it yet. Per MSVC documentation it is safe to ignore the warnings for the STL. Many of the warnings apply to things like std::vector<std::string>>. Other warnings occur because, according to the warnings, the Imath classes are not declared for export. Since we are exporting by member, not class on Windows, this issue results; the conflict is that the attribute templates are exported at a class level, but the parameterized types are not. I'm not sure if this is resolvable in a reasonable way. Per MSVC documentation, this warning can be ignored if there are no static members in the base. So, for now, my proposal is that we suppress the warnings with pragmas.

- in headers, I push/pop pragmas for msvc, but not in cpp files.

- _CRT_SECURE_NO_WARNINGS as a macros seems broken currently - this is the annoying thing where msvc is compelled to tells us that strcpy and printf are not safe, and we should use strcpy_s instead. This is annoying, and we are protected by fuzz testing. So I've suppressed it with a pragma warning suppression on 4996.

- there are a great many narrowing warnings from int64_t and ptrdiff_t to int or long. I've static_casted a bunch of them, but I think that probably we need to work these through more properly. Are the routines with int in their parameter list, receiving int64_t values, more properly written with int64_t parameters? The static_casting makes the warnings go away, doesn't change the behavior, and gives us an easy grep to find all the problem areas. This is the main reason I think we might need a 3.1 release, because I'm sure we will find at least a few interfaces that need updating. 

I have attached here a log, which can be diffed against the log in #982, to see the number of lines of output reduced from 4500 to 4100.

[spew3.txt](https://github.com/AcademySoftwareFoundation/openexr/files/6177010/spew3.txt)

### CODE REVIEW

**Review by cary-ilm — APPROVED** [review]
LGTM.

Although, it sure would be nice to eliminate many of these static_cast's by making the use of int vs. size_t vs. other index types consistent for fields/variables/parameters wherever possible, but that's a bigger task.  Looks like DWACompressor has parameter int while B44Compressor has size_t.

**Comment by meshula** [comment]
lines of output now reduced to 1700 :) All the dll warnings have been cleaned.

**Comment by meshula** [comment]
@cary-ilm @jmertic  I'm ready to land this ~ is there a lever we can pull to unblock EasyCLA? I'm signed for CLA 2.1 and can already land successfully in the Imath repo.

**Comment by cary-ilm** [comment]
The CLA failure is a glitch, I will merge in spite of it.

**Comment by meshula** [comment]
Fantastic! Didn't realize that was an option :)

**Pull request merged**
