### PR TITLE
Take DESTDIR into account when creating library symlinks

### PR DESCRIPTION
**Pull request by antonio-rojas**
Currently cmake tries to create the symlinks directly on the root filesystem, which fails if installing to a specific DESTDIR

### CODE REVIEW

**Review by meshula — CHANGES_REQUESTED** [review]
Question on intent in the Conversation thread.

**Comment by meshula** [comment]
According to the kitware (https://gitlab.kitware.com/cmake/cmake/issues/17340), on *nix, variables with the key _FULL_ in them are always rooted in /usr/local. Is the intent of this change that if the user has set DESTDIR to say/ foo, then the symlinks become /foo/usr/local? Generally it seems that kitware suggests CMAKE_INSTALL_PREFIX for this purpose, then CMAKE_INSTALL_FULL_DIR would resolve as you need? Or am I misunderstanding this diff?

**Comment by antonio-rojas** [comment]
> Is the intent of this change that if the user has set DESTDIR to say/ foo, then the symlinks become /foo/usr/local?

No. The symlinks are relative, and this doesn't change that. The intent is that in case you are make-installing to a specific DESTDIR (ie. for creating a distro package) the symlink is created inside the filesystem of such DESTDIR, and not in the build machine's filesystem.

**Comment by meshula** [comment]
Ok, thanks for the explanation, it helps me understand what's going on. I'll leave it for someone more knowledgeable about distro packaging to review.

**Comment by cary-ilm** [comment]
This doesn't seem quite right. @kdt3rd is going to investigate, there seems to be something wrong with how the pkg-config is generated that's causing downstream problems.

**Comment by kdt3rd** [comment]
These changes look good. I always forget that cmake_install_prefix isn't overwritten by destdir but instead prepended in front for chroot-like behavior. Thanks for the fix!

**Pull request merged**
