### PR TITLE
OpenEXR/ImfStdIO.[cpp h]: Added StdISStream.

### PR DESCRIPTION
**Pull request by arkellr**
This class was missing; ie the "input" stringstream version of StdOSStream.
Based off istringstream.

Signed-off-by: Arkell Rasiah <arasiah@pixsystem.com>

### CODE REVIEW

**Review by cary-ilm — APPROVED** [review]

**Comment by cary-ilm** [comment]
I hate to be a pest, but could you add a test for this? In IlmImfTest/testExistingStreams.cpp? It could sit alongside the existing tests.

**Comment by arkellr** [comment]
np... i will put together something... if i recall right stdostream didnt hv a test of it too... so will roll something that does both.

**Comment by cary-ilm** [comment]
Pinging @arkellr again, any chance you can find some time to put a test together for this?

**Comment by arkellr** [comment]
... actually made a ticket for this in my current work sprint... and actually will likely start on it tomorrow...

**Comment by arkellr** [comment]
Cary test case added for Imf::StdOSStream/StdISStream... let me know if you would like to do a zoom to review the updates to testExistingStreams.cpp.

**Review by cary-ilm — APPROVED** [review]
LGTM

**Pull request merged**
