### PR TITLE
Fix MSVC 2022 build

### PR DESCRIPTION
**Pull request by remia**
Fix for #1236.

Note: I don't have access to Visual Studio 2022 and rely on CI to validate it.

### CODE REVIEW

**Comment by meshula** [comment]
This looks good to me, thanks! Looks like there's some issue to resolve with the EasyCLA set up?

**Comment by remia** [comment]
Solved the CLA issue, hoping to see the CI builds running to validate the changes!

**Comment by meshula** [comment]
Nice! It's working :) Thanks!

**Comment by lgritz** [comment]
It would be helpful to backport this to 3.1.

GHA is retiring the "windows-2016" image imminently, so I think a lot of projects are going to revisit their Windows CI and in the process start to get the windows-2022 image in their I matrix, and will immediately run into this present issue (as I did today). So a 3.1.5 that is safe to build with VS2022 will probably start to become more important.

**Pull request merged**
