### PR TITLE
Resolve #882 static/shared dual build

### LINKED ISSUE #882: BUILD_SHARED/STATIC should not be automatic.
From issue https://github.com/AcademySoftwareFoundation/openexr/issues/881

Please don't set BUILD_SHARED_LIBS if you're not the top-level project. An easy check is to compare the CMAKE_CURRENT_SOURCE_DIR with CMAKE_SOURCE_DIR and not turn on global options if it's a submodule. Instead, please add a prefixed option like OPENEXR_BUILD_SHARED or similar. That should be fairly easy to use given ILMBASE_DEFINE_LIBRARY is the entry point for library definitions, and you can simply select the library type there:

```cmake
  if(OPENEXR_BUILD_SHARED_LIBS)
    set(OPENEXR_LIB_TYPE SHARED)
  else()
    set(OPENEXR_LIB_TYPE STATIC)
  endif()
  add_library(${objlib} ${OPENEXR_LIB_TYPE}
    ${ILMBASE_CURLIB_HEADERS}
    ${ILMBASE_CURLIB_SOURCES})
```

For issues resulting from confusion or issues resulting from building both static and dynamic libs see also:

https://github.com/AcademySoftwareFoundation/openexr/issues/748
https://github.com/AcademySoftwareFoundation/openexr/issues/833
https://github.com/AcademySoftwareFoundation/openexr/issues/856
https://github.com/AcademySoftwareFoundation/openexr/issues/871

If we remove heuristics about which build to make, and make the shared library automatic on linux, otherwise default to static, the majority of first-time user problems will be resolved.

### PR DESCRIPTION
**Pull request by meshula**
Resolves https://github.com/AcademySoftwareFoundation/openexr/issues/882

### CODE REVIEW

**Comment by lgritz** [comment]
LGTM, but we should get group consensus about whether it's ok to lose the ability to produce both static and shared libraries in a single build. Somebody put it there for a reason, we need to make sure that they either no longer want this feature or no longer want to argue that the extra build script complexity is worth the trouble.

**Comment by meshula** [comment]
Makes sense ~ hopefully that conversation can be resolved, and the CLA as well around the same time :)

AFAICR the original "do both" impetus is Windows specific, and came from when we were having the OpenEXR build produce the b44 tables, rather than having them precomputed and checked in. The Windows build was eternally dogged by getting the DLLs into the right place so that the helper program would run across multiple build environments and CI. Producing a static library resolved that build problem definitively at the expense of making the build work both ways. Now that we check in the generated files, the one reason that I personally know of to have this static/shared build has gone away.

**Review by cary-ilm — APPROVED** [review]
LGTM, pending the CLA

**Comment by cary-ilm** [comment]
Resolved by #942

**Pull request closed without merging**
