### PR TITLE
Fix macOS ARM64/x86_64 universal 2 build

### PR DESCRIPTION
**Pull request by hjmallon**
Somehow part of my previous PR (https://github.com/AcademySoftwareFoundation/openexr/pull/854) got lost in the big 3.0 move I think.

### CODE REVIEW

**Comment by meshula** [comment]
Thanks for the fix. Does the CLA need to be resigned due to the migration from CLA 2.0 to CLA 2.1?

**Comment by hjmallon** [comment]
I'm in progress on sorting out getting myself onto our corporate CLA. Since this is a cherry pick of part of my previous PR (which was under a valid CLA) I don't mind if it just finds its way into master and I can close this PR.

**Comment by hjmallon** [comment]
Closing as the CLA has changed so our corp CLA sign thing has expired.

**Comment by cary-ilm** [comment]
Does ##1011 look right?  Apologies for the omission.

**Comment by hjmallon** [comment]
Thanks @cary-ilm . I will start the process of signing the new CLA for future stuff.

**Pull request closed without merging**
