### PR TITLE
Fixing Imath automatic install

### PR DESCRIPTION
**Pull request by owdt-magic**
Adjusting the automatic install of Imath to include the correct directories. This could potentially fix the issues with CI.
Signed-off-by: Owen Thompson <oxt3479@rit.edu>

### CODE REVIEW

**Comment by cary-ilm** [comment]
A couple gotchas:

src/test/OpenEXRFuzzTest/fuzzFile.cpp has #include "../IlmImfTest/TestUtilFStream.h".
This is bad form to directly include a file this way from another directory, but even worse, the directory name is incorrect and should be "OpenEXRTest". At the very least, fix that for now and let's straighten out the #include "../" later.

IexTest/CMakeLists.txt references "IlmBase.Iex", that should now be OpenEXR.Iex.

**Comment by kthurston** [comment]
We should also not be using global include / link directories, but rather per-targets and Imath modules. Additionally, I don't think we should use a git submodule, but rather  external project directly...

**Review by meshula — APPROVED** [review]
lgtm

**Comment by owdt-magic** [comment]
These changes should not be integrated yet. I will be taking a different approach for the installation in the coming days.

**Pull request merged**
