### PR TITLE
Fix OPENEXR_VERSION_HEX

### PR DESCRIPTION
**Pull request by cary-ilm**
* fix syntax error
* remove unnecessary uint32_t cast
* add validation test

Addresses #1537

### CODE REVIEW

**Review by meshula — APPROVED** [review]
looks fine, and won't need a second look until we reach OpenEXR 128.0.0 where we might discover negative versions. I'm not spotting the syntax error though?

**Comment by cary-ilm** [comment]
In C++ code,  the type can act like a function, e.g. `uint32_t(x)`, but that doesn't work in a macro, so 
`uint32_t v = OPENEXR_VERSION_HEX;`
is fine, but:
`#if OPENEXR_VERSION_HEX > 0` 
reports a syntax error because it thinks `uint32_t` is a macro function. But the type casts shouldn't be necessary anyway.

My test didn't actually verify that case, so I added an `#if`.

**Comment by meshula** [comment]
Oh! TIL....

**Comment by lgritz** [comment]
I don't think it's because it "thinks it's a macro." It's because macros are not C++ interpreters. All they do is text substitution of macro definitions and a handful of text/numerical ops like `==`, `<<`, `|`.  A conditional compilation directive like `#if uint32_t(x) ...` fails for the same reason why `#if sin(x)...` --- it's not C++ and it can't evaluate function calls, constructors, etc.

**Pull request merged**
