### PR TITLE
Disable OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX when building on arm64 macOS

### PR DESCRIPTION
**Pull request by betajippity**
For some reason, the compile check for detecting inline AVX support does
not correctly disable OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX when building
on arm64 macOS using clang (the check does work correctly on aarch64 Linux
using gcc). This change hardcodes OPENEXR_IMF_HAVE_GCC_INLINE_ASM_AVX to
always be false when the system is detected as arm64 macOS. This change
is necessary to allow building on arm64 macOS to complete successfully.

### CODE REVIEW

**Review by meshula — APPROVED** [review]
Ain't no AVX on ARM!

**Comment by meshula** [comment]
@betajippity Could you do the DCO thing? I believe you have to amend the commit with some boilerplate.

**Comment by betajippity** [comment]
@meshula I thought I already did the DCO thing? Or do I have to do it again?

**Comment by meshula** [comment]
Must have been an automation glitch! Everything is green now :)

**Comment by LxLasso** [comment]
But.. what if you are building for multiple architectures? I may be confused, my cmake knowledge is low and after running cmake we build in Xcode, but this fix would appear to disable AVX only if building arm64 only? (My dirty fix is adding `#if !defined(__arm64__)` in OpenEXRConfigInternal.h.)

**Pull request merged**
