### PR TITLE
fix out of bounds check with a full channel name vs. byte count

### PR DESCRIPTION
**Pull request by kdt3rd**

### CODE REVIEW

**Review by cary-ilm — APPROVED** [review]
LGTM

**Comment by cary-ilm** [comment]
Should we rush this into v3.1.8?

**Comment by meshula** [comment]
If the Occam's Razor here is "does it eliminate a possible memory corruption", the answer is no. If the Razor is "does the fix match the C++ behavior" the answer is yes as a string with length 127 won't be rejected as corrupt by the C++ version of the code (Assuming I read the C++ code properly just now). So I think that's a compelling reason to merge it.

**Comment by kdt3rd** [comment]
@cary-ilm yes, we need to put this into 3.1.8 - it was actually a bug that OSS fuzz found, but I didn't have the number when fixing...

**Pull request merged**
