### PR TITLE
Allow the use of Pthreads with WIN32/64 builds under MinGW

### PR DESCRIPTION
**Pull request by meshula**

### CODE REVIEW

**Comment by lgritz** [comment]
Can we give this a better title?

**Comment by meshula** [comment]
@lgritz embettered.

**Comment by cary-ilm** [comment]
This looks good to me, @meshula can you get your CLA squared away?

**Comment by cary-ilm** [comment]
@meshula, We'd like to get this into the 2.5 release. Can you resolve the CLA issue?

**Review by cary-ilm — APPROVED** [review]
LGTM

**Comment by cary-ilm** [comment]
@meshula, something got mangled in the merge here, but rather than try to untangled it, I diff'ed your changes into a fresh PR, can you try out #707 and confirm it behaves properly, the same as #673? If so, give it a review and I'll merge it into 2.5.0, then close #673 out.

**Comment by cary-ilm** [comment]
This has been covered by #707.

**Pull request closed without merging**
