### PR TITLE
Use absolute directory names in pkg-config files for CMake builds.

### LINKED ISSUE #567: CMake builds produce invalid pkg-config files
After updating IlmBase and OpenEXR to 2.4.0 and changing to CMake, IlmBase.pc and OpenEXR.pc contains bogus entries for `libdir`, etc.

Before:

```
$ cat IlmBase.pc
prefix=/gnu/store/p78hb0ifsam4d6l20sj69wzn262myx67-ilmbase-2.3.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
OpenEXR_includedir=${prefix}/include/OpenEXR

Name: IlmBase
Description: Base math and exception libraries
Version: 2.3.0
Libs: -L${libdir} -lImath -lHalf -lIex -lIexMath -lIlmThread -pthread
Cflags: -pthread -I${OpenEXR_includedir}

$ cat OpenEXR.pc
prefix=/gnu/store/i2gxm1zpz1yqcinycv85mjxiw99vqzy4-openexr-2.3.0
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include
OpenEXR_includedir=${prefix}/include/OpenEXR

Name: OpenEXR
Description: OpenEXR image library
Version: 2.3.0

Libs: -L${libdir} -lIlmImf
Cflags: -I${OpenEXR_includedir}
Requires: IlmBase
Libs.private: -lz
```

After:
```
$ cat IlmBase.pc
prefix=/gnu/store/zfqx6sd92bjxpfzq7wii7hn5f34s18qm-ilmbase-2.4.0
exec_prefix=bin
libdir=lib
includedir=include
libsuffix=-2_4
Name: IlmBase
Description: Base math and exception libraries
Version: 2.4.0
Requires:
Conflicts:
Libs: -L${libdir} -lImath${libsuffix} -lHalf${libsuffix} -lIex${libsuffix} -lIexMath${libsuffix} -lIlmThread${libsuffix} -pthread
Cflags: -pthread -I${includedir} -I${includedir}/OpenEXR

$ cat OpenEXR.pc
prefix=/gnu/store/qlijvn28x8h6fv85ph1p91c337hvf5dx-openexr-2.4.0
exec_prefix=bin
libdir=lib
includedir=include
OpenEXR_includedir=include/OpenEXR
libsuffix=-2_4

Name: OpenEXR
Description: OpenEXR image library
Version: 2.4.0

Libs: -L${libdir} -lIlmImf${libsuffix}
Cflags: -I${OpenEXR_includedir}
Requires: IlmBase
Libs.private: -lz
```

IlmBase and OpenEXR are built separately.  It's not clear to me why `$prefix` is missing from the newer pkg-config files.  Ideas?

### PR DESCRIPTION
**Pull request by mbakke**
Fixes #567.

### CODE REVIEW

**Comment by equal-l2** [comment]
Any progress here?

**Comment by kdt3rd** [comment]
fyi, I have put in a separate / different PR that injects the ${prefix} variables as is common style in the pkg-config files. I think that would be the more appropriate way to address this, do you agree?

**Comment by kdt3rd** [comment]
Hey, I've gone ahead and merged in the version where we inject the prefix variable, as that seems to be more what other pkg-config files look like, so that seemed more consistent. Thanks for tracking this down and suggesting a fix, it is much appreciated!

**Comment by mbakke** [comment]
Thanks for improving on my lazy fix! :-)

**Pull request closed without merging**
