### PR TITLE
Update README.md for nuget documentation

### LINKED ISSUE #345: nuget documentation
Requires clear information in Readme for nuget usage with Visual Studio and MSbuild. Also requires continuous integration usage instructions.

### PR DESCRIPTION
**Pull request by ghost**
resolve https://github.com/openexr/openexr/issues/345

edit: preview here
https://github.com/openexr/openexr/tree/8ad94f6b4c20c5fb2831d0cd083158613acd802b

### CODE REVIEW

**Comment by cary-ilm** [comment]
@coast77777777777, this is great, thanks for contributing. Could we invite you to the next steering committee meting to discuss in person? Thursday, August 8, 1pm PDT via Zoom, the meeting info is on the ASWF calendar here: https://lists.aswf.io/g/openexr-dev/viewevent?repeatid=15006&eventid=494941&calstart=2019-08-08

**Comment by ghost** [comment]
Greetings Cary,

I’m happy to contribute as needed and I should be able to attend the zoom meeting on August 8. 

Thanks,
Rob

**Comment by cary-ilm** [comment]
Checking back on this PR, the nuget instructions are a good addition, but it seems that they'd go better as a section in INSTALL.md, rather than in the FAQ.

**Comment by ghost** [comment]
Ok I will make the changes. Thanks for direction.

**Comment by cary-ilm** [comment]
Closing this for now, it seems to have gone stale.

**Pull request closed without merging**
