### PR TITLE
fix example

### LINKED ISSUE #1711: Python crashes when trying to write an output file
I'm running the example code from the README:
```
import OpenEXR, Imath

width = 10
height = 10
size = width * height

h = OpenEXR.Header(width,height)
h['channels'] = {'R' : Imath.Channel(Imath.PixelType.FLOAT),
                 'G' : Imath.Channel(Imath.PixelType.FLOAT),
                 'B' : Imath.Channel(Imath.PixelType.FLOAT),
                 'A' : Imath.Channel(Imath.PixelType.FLOAT)} 
o = OpenEXR.OutputFile("hello.exr", h)
r = array('f', [n for n in range(size*0,size*1)]).tobytes()
g = array('f', [n for n in range(size*1,size*2)]).tobytes()
b = array('f', [n for n in range(size*2,size*3)]).tobytes()
a = array('f', [n for n in range(size*3,size*4)]).tobytes()
channels = {'R' : r, 'G' : g, 'B' : b, 'A' : a}
o.writePixels(channels)
o.close()
```

When I get to the `OpenEXR.OutputFile`, I get a "Python has stopped working" dialog box, or a Jupyter dialog box "The kernel has stopped unexpectedly."

I'm running on 64-bit Miniconda on Windows 11, in a clean environment where I just installed python and jupyter, then pip installed OpenEXR.  I tried Python 3.12, then made a new environment with Python 3.7 (since that's the oldest version supported by the pyproject.toml).  I also tried in conda environments on a different computer running Windows Server 2016.  None of this works.

There's also a conda OpenEXR on conda-forge.  I tried with and without that; I'm not sure what it is, but installing it is not sufficient to `import OpenEXR` without also pip installing OpenEXR.

Please let me know if there's any more info, or tests I can run, that would be useful in debugging.

### PR DESCRIPTION
**Pull request by hroskes**
and raise error when running the buggy version
instead of python mysteriously crashing

fixes #1711

### CODE REVIEW

**Comment by hroskes** [comment]
I'm trying to figure out who from my institution I should reach out to about the CLA. I'm hoping to get back to you about that later today.

**Comment by hroskes** [comment]
Also, I'm pretty sure the doctest is way outdated and not used anymore (it still has python 2 print), but I figured I'd update it anyway and you can use it if you ever decide to turn those back on.

**Review by cary-ilm — APPROVED** [review]
Thanks for the fix, both for the example code and the error handling. We recently inherited this code, and it's indeed quite old.  We're working on an upgrade, but it's good to have it fixed in the meantime.

I'll merge as soon as you can complete the CLA. Thanks again!

**Comment by cary-ilm** [comment]
@hroskes, will you be able to sign the CLA? I'd like to merge this if you can. If it's too much of a hassle I can make the fix independently. Thanks!

**Comment by hroskes** [comment]
I'm sorry, I'm working on it!  There should be a trivial procedure to deal with trivial changes like this one, and there probably is but I'm having trouble figuring out what that is.  Still iterating with the people at my institution.

**Comment by hroskes** [comment]
@cary-ilm We got the CLA signed.  Thanks so much and I'm sorry for the long delay!

**Comment by hroskes** [comment]
@cary-ilm Just wanted to ping you again.  Is anything else needed from my side?

Again, thank you and I apologize for the delay.

**Review by cary-ilm — APPROVED** [review]
LGTM

**Pull request merged**
