### PR TITLE
Bazel support: Update Imath to 3.1.8

### PR DESCRIPTION
**Pull request by Vertexwahn**
This PR only affects the Bazel Build of OpenEXR:

- Update of Imath to 3.1.8
- Reformat Bazel files
- Update Bazel version

### CODE REVIEW

**Review by cary-ilm — APPROVED** [review]
LGTM, thanks.

**Comment by cary-ilm** [comment]
@Vertexwahn, I merged this into v3.1.8 but it looks like that caused problems for the Bazel build, was that not correct? Should I back it out, or can you provide a fix? Thanks.

**Comment by Vertexwahn** [comment]
@cary-ilm  Which branch is 3.1.8? `release`or `RB-3.1`?

**Comment by cary-ilm** [comment]
RB-3.1

V3.1.8-rc2 is a tag currently at the head of RB-3.1

**Comment by Vertexwahn** [comment]
@cary-ilm See here: https://github.com/AcademySoftwareFoundation/openexr/pull/1437

**Pull request merged**
