### PR TITLE
Cherry-pick PRs and release notes for v2.4.3

### PR DESCRIPTION
**Pull request by cary-ilm**

### CODE REVIEW

**Comment by meshula** [comment]
I can't find the problems in the mac logs, but in the linux log there's this -
```
45%] Building CXX object OpenEXR/IlmImf/CMakeFiles/IlmImf.dir/ImfScanLineInputFile.cpp.o
[ 45%] Building CXX object OpenEXR/IlmImf/CMakeFiles/IlmImf.dir/ImfTiledInputFile.cpp.o
/__w/1/s/OpenEXR/IlmImf/ImfScanLineInputFile.cpp: In member function 'void Imf_2_4::ScanLineInputFile::initialize(const Imf_2_4::Header&)':
/__w/1/s/OpenEXR/IlmImf/ImfScanLineInputFile.cpp:1114:35: error: cannot convert 'Imf_2_4::Compression' to 'Imf_2_4::Compressor*' for argument '1' to 'int Imf_2_4::numLinesInBuffer(Imf_2_4::Compressor*)'
             numLinesInBuffer (comp);
                                   ^
/__w/1/s/OpenEXR/IlmImf/ImfScanLineInputFile.cpp:1127:53: error: 'gLargeChunkTableSize' was not declared in this scope
         if (lineOffsetSize * _data->linesInBuffer > gLargeChunkTableSize)
                                                     ^~~~~~~~~~~~~~~~~~~~
/__w/1/s/OpenEXR/IlmImf/ImfScanLineInputFile.cpp:1173:13: error: redeclaration of 'int lineOffsetSize'
         int lineOffsetSize = (dataWindow.max.y - dataWindow.min.y +
             ^~~~~~~~~~~~~~
/__w/1/s/OpenEXR/IlmImf/ImfScanLineInputFile.cpp:1116:13: note: 'int lineOffsetSize' previously declared here
         int lineOffsetSize = (dataWindow.max.y - dataWindow.min.y +
             ^~~~~~~~~~~~~~
OpenEXR/IlmImf/CMakeFiles/IlmImf.dir/build.make:694: recipe for target 'OpenEXR/IlmImf/CMakeFiles/IlmImf.dir/ImfScanLineInputFile.cpp.o' failed
gmake[2]: *** [OpenEXR/IlmImf/CMakeFiles/IlmImf.dir/ImfScanLineInputFile.cpp.o] Error 1
gmake[2]: *** Waiting for unfinished jobs....
[ 45%] Building CXX object PyIlmBase/PyImath/CMakeFiles/PyImath_Python2_7.dir/PyImathPlane.cpp.o
```

**Comment by cary-ilm** [comment]
My bad, I missed some commits. Retrying now.

**Comment by meshula** [comment]
Windows is failing on not being able to retrieve a boost archive. 

```

Mode                LastWriteTime         Length Name                                                                  
----                -------------         ------ ----                                                                  
d-----        5/12/2021   9:57 PM                _boost                                                                
Retrieving http://dl.bintray.com/boostorg/release/1.66.0/source/boost_1_66_0.zip
Invoke-WebRequest : Forbidden!
At D:\a\1\s\share\ci\scripts\windows\install_boost.ps1:23 char:1
+ Invoke-WebRequest $boostArchive -OutFile "boost-${boostVersion}.zip"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (System.Net.HttpWebRequest:HttpWebRequest) [Invoke-WebRequest], WebExc 
   eption
```

**Review by meshula — APPROVED** [review]
I don't think the CI failures have anything to do with this change.

**Comment by cary-ilm** [comment]
@meshula, I believe that's true. Because it's RB-2.4, it's triggering the old Azure build. Just to confirm before release, can you try downloading the branch to Windows and making sure it builds?

**Comment by meshula** [comment]
Done ~ it builds and installs successfully on Windows.

**Pull request merged**
