### PR TITLE
Corrected grammar mistakes

### PR DESCRIPTION
**Pull request by gargarchit**
Corrected grammar mistakes

### CODE REVIEW

**Comment by gargarchit** [comment]
Hello, @kdt3rd , @cary-ilm @lgritz @meshula ,
I am interested in GSOC for the project **OpenEXR: New python bindings for Imath using pybind11.** 
Currently, I am preparing a proposal for it. Also, I want to know how should I contact with the community.

**Comment by gargarchit** [comment]
Hello, @lgritz @cary-ilm , I am interested in GSOC for the project OpenEXR: New python bindings for Imath using pybind11. I have prepared a Proposal and submitting draft through GSoC. Also, I want to know how should I contact with the community.

**Comment by cary-ilm** [comment]
Hi @gargarchit, we see your GSoC project proposal, and we are in the process now of evaluating the proposals we've received. You should hear back soon via the GSoC administration. 

In the meantime, you can contact the project community via openexr-dev@lists.aswf.io.

Regarding this PR, other than merging a few lines together, I don't see any actual change to the text. Am I missing something? For the purpose of the GSoC application requirement, it's fine, although before merging it I'd like to understand what the change actually is. Thanks!

**Comment by lgritz** [comment]
There are a few typo fixes, @cary-ilm 

But those fixes should have been done in isolation, there was no reason why any of the text should have been re-wrapped without needing any changes. I would rather see those extraneous changes removed from this PR and only include the legit spelling or grammar fixes.

**Comment by gargarchit** [comment]
Hi @cary-ilm, There are some typos fix and I removed extra spaces and a new blank line. This was just done to improve the ReadMe for documentation.
Also, Thanks I will be in contact with the project community, Hope there will be great GSoC 2020.

**Comment by cary-ilm** [comment]
@gargarchit, thanks for the fixes. This corrects the misspelling of "Governance" and "information" (thanks!). Can you re-submit with *just* those two changes, without the other whitespace changes?

**Comment by cary-ilm** [comment]
Since we hadn't heard back from you on a version of this without the whitespace changes, I corrected the misspellings and submitted as a separate PR, so closing this. Thanks for spotting the errors.

**Pull request closed without merging**
