### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by aclark4life**
Website preview: https://openexr--1690.org.readthedocs.build/en/1690/

### CODE REVIEW

**Comment by aclark4life** [comment]
👍 

Screenshot 2024-03-22 at 9 53 32 PM

Only problem now is dark styles are incomplete and not sure if auto load is working, I get dark by default now at least. May need to fix this in sphinx-press-theme 0.9.2 particularly if it is a blocker for OEXR deployment.

**Comment by cary-ilm** [comment]
Thanks! I do prefer the dark style, glad to see it as an option, and also fine if it's the default. Where are you noticing it's incomplete?

The ASWF logo in the page footers is dark so doesn't read in dark mode. There's a white version at  https://artwork.aswf.io/other/aswf/logo/black/aswf-logo-white.svg, can it be configured to choose depending on the mode?
or there's a gold option at https://artwork.aswf.io/other/aswf/logo/gold/aswf-logo-gold.svg which might work in light and dark.

**Comment by aclark4life** [comment]
> Thanks! I do prefer the dark style, glad to see it as an option, and also fine if it's the default. Where are you noticing it's incomplete?

For example the text on the warning alert needs to be made dark mode specific so that is readable. That's a CSS fix somewhere.


Screenshot 2024-03-25 at 9 52 26 AM

> The ASWF logo in the page footers is dark so doesn't read in dark mode. There's a white version at https://artwork.aswf.io/other/aswf/logo/black/aswf-logo-white.svg, can it be configured to choose depending on the mode? or there's a gold option at https://artwork.aswf.io/other/aswf/logo/gold/aswf-logo-gold.svg which might work in light and dark.

I would say that in the short term, if you could merge and change the logo to gold that would be my preference, just to get it out there. However,  if there is anything you can't live with in the short term, let me know and I'll try to fix. The rest of proposed changes (CSS fixes, logo configurability, etc) can go in a future release of sphinx-press-theme. 😎

**Comment by aclark4life** [comment]
Newer version deployed! Probably don't need this anymore.

**Pull request closed without merging**
